export const maharashtraDistricts = {
  'Ahmednagar': ['Ahmednagar', 'Akole', 'Jamkhed', 'Karjat', 'Kopargaon', 'Nevasa', 'Parner', 'Pathardi', 'Rahata', 'Rahuri', 'Sangamner', 'Shevgaon', 'Shrigonda', 'Shrirampur'],
  'Akola': ['Akola', 'Akot', 'Balapur', 'Barshitakli', 'Murtijapur', 'Patur', 'Telhara'],
  'Amravati': ['Achawal', 'Amravati', 'Anjangaon Surji', 'Bhatkuli', 'Chandur Bazar', 'Chandur Railway', 'Chikhaldara', 'Daryapur', 'Dhamangaon Railway', 'Dharni', 'Morshi', 'Nandgaon Khandeshwar', 'Teosa', 'Warud'],
  'Aurangabad': ['Aurangabad', 'Gangapur', 'Kannad', 'Khuldabad', 'Paithan', 'Phulambri', 'Sillod', 'Soegaon', 'Vaijapur'],
  'Beed': ['Ambejogai', 'Ashti', 'Bid', 'Dharur', 'Georai', 'Kaij', 'Manjlegaon', 'Parli', 'Patoda', 'Shirur', 'Wadwani'],
  'Bhandara': ['Bhandara', 'Lakhandur', 'Lakhani', 'Mohadi', 'Pauni', 'Sakoli', 'Tumsar'],
  'Buldhana': ['Buldhana', 'Chikhli', 'Deulgaon Raja', 'Jalgaon Jamod', 'Khamgaon', 'Lonar', 'Malkapur', 'Mehkar', 'Motala', 'Nandura', 'Sangrampur', 'Shegaon', 'Sindkhed Raja'],
  'Chandrapur': ['Ballarpur', 'Bhadravati', 'Brahmapuri', 'Chandrapur', 'Chimur', 'Gondpipri', 'Jiwati', 'Korpana', 'Mul', 'Nagbhid', 'Pombhurna', 'Rajura', 'Sawali', 'Sindewahi', 'Warora'],
  'Dhule': ['Dhule', 'Malegaon', 'Sakri', 'Shirpur', 'Sindkhede'],
  'Gadchiroli': ['Aheri', 'Armori', 'Bhamragad', 'Chamorshi', 'Desaiganj', 'Dhanora', 'Etapalli', 'Gadchiroli', 'Kurkheda', 'Mulchera', 'Sironcha', 'Wadsa'],
  'Gondia': ['Amgaon', 'Arjuni Morgaon', 'Deori', 'Gondia', 'Goregaon', 'Sadak Arjuni', 'Salekasa', 'Tirora'],
  'Hingoli': ['Aundha', 'Basmath', 'Hingoli', 'Kalamnuri', 'Sengaon'],
  'Jalgaon': ['Amalner', 'Bhadgaon', 'Bhusawal', 'Bodwad', 'Chalisgaon', 'Chopda', 'Dharangaon', 'Erandol', 'Jalgaon', 'Jamner', 'Muktainagar', 'Pachora', 'Parola', 'Raver', 'Yawal'],
  'Jalna': ['Ambad', 'Badnapur', 'Bhokardan', 'Ghansawangi', 'Jafferabad', 'Jalna', 'Mantha', 'Partur'],
  'Kolhapur': ['Ajra', 'Bavda', 'Bhudargad', 'Chandgad', 'Gadhinglaj', 'Hatkanangale', 'Kagal', 'Karvir', 'Kolhapur', 'Panhala', 'Radhanagari', 'Shahuwadi', 'Shirol'],
  'Latur': ['Ahmadpur', 'Ausa', 'Chakur', 'Deoni', 'Jalkot', 'Latur', 'Nilanga', 'Renapur', 'Shirur Anantpal', 'Udgir'],
  'Mumbai City': ['Area not divided into Talukas'],
  'Mumbai Suburban': ['Andheri', 'Borivali', 'Kurla'],
  'Nagpur': ['Bhiwapur', 'Hingna', 'Kalameshwar', 'Kamthi', 'Kuhi', 'Mauda', 'Nagpur Rural', 'Nagpur Urban', 'Narkhed', 'Parseoni', 'Ramtek', 'Savner', 'Umred'],
  'Nanded': ['Ardhapur', 'Bhokar', 'Biloli', 'Deglur', 'Dharmabad', 'Hadgaon', 'Himayatnagar', 'Kandhar', 'Kinwat', 'Loha', 'Mahur', 'Mudkhed', 'Mukhed', 'Naigaon', 'Nanded', 'Umri'],
  'Nandurbar': ['Akkalkuwa', 'Akrani', 'Nandurbar', 'Navapur', 'Shahade', 'Talode'],
  'Nashik': ['Baglan', 'Chandvad', 'Deola', 'Dindori', 'Igatpuri', 'Kalwan', 'Malegaon', 'Nandgaon', 'Nashik', 'Niphad', 'Peint', 'Sinnar', 'Sula', 'Surgeana', 'Trimbakeshwar', 'Yevla'],
  'Osmanabad': ['Bhum', 'Kalamb', 'Lohara', 'Osmanabad', 'Paranda', 'Tuljapur', 'Umarga', 'Washi'],
  'Palghar': ['Dahanu', 'Jawhar', 'Mokhada', 'Palghar', 'Talasari', 'Vasai', 'Vikramgad'],
  'Parbhani': ['Gangakhed', 'Jintur', 'Manwath', 'Palam', 'Parbhani', 'Pathri', 'Purna', 'Sailu', 'Sonpeth'],
  'Pune': ['Ambegaon', 'Baramati', 'Bhor', 'Daund', 'Haveli', 'Indapur', 'Junnar', 'Khed', 'Mawal', 'Mulshi', 'Pune City', 'Purandhar', 'Shirur', 'Velhe'],
  'Raigad': ['Alibag', 'Karjat', 'Khalapur', 'Mahad', 'Mangaon', 'Mhasla', 'Murud', 'Panvel', 'Pen', 'Poladpur', 'Roha', 'Shrivardhan', 'Sudhagad', 'Tala', 'Uran'],
  'Ratnagiri': ['Chiplun', 'Dapoli', 'Guhagar', 'Khed', 'Lanja', 'Mandangad', 'Rajapur', 'Ratnagiri', 'Sangameshwar'],
  'Sangli': ['Atpadi', 'Jat', 'Kadegaon', 'Kavathe Mahankal', 'Khanapur', 'Miraj', 'Palus', 'Sangli', 'Shirala', 'Tasgaon', 'Walwa'],
  'Satara': ['Jaoli', 'Karad', 'Khandala', 'Khatav', 'Koregaon', 'Mahabaleshwar', 'Man', 'Patan', 'Phaltan', 'Satara', 'Wai'],
  'Sindhudurg': ['Devgad', 'Dodamarg', 'Kankavli', 'Kudal', 'Malwan', 'Sawantwadi', 'Vaibhavwadi', 'Vengurla'],
  'Solapur': ['Akkalkot', 'Barshi', 'Karmala', 'Madha', 'Malshiras', 'Mangalvedhe', 'Mohol', 'Pandharpur', 'Sangole', 'Solapur North', 'Solapur South'],
  'Thane': ['Ambarnath', 'Bhiwandi', 'Kalyan', 'Murbad', 'Shahapur', 'Thane', 'Ulhasnagar'],
  'Wardha': ['Arvi', 'Ashti', 'Deoli', 'Hinganghat', 'Karanja', 'Samudrapur', 'Seloo', 'Wardha'],
  'Washim': ['Karanja', 'Malegaon', 'Mangrulpir', 'Manora', 'Risod', 'Washim'],
  'Yavatmal': ['Arni', 'Babulgaon', 'Darwha', 'Digras', 'Ghatanji', 'Kalamb', 'Kelapur', 'Lohara', 'Mahagaon', 'Maregaon', 'Ner', 'Pusad', 'Ralegaon', 'Umarkhed', 'Wani', 'Yavatmal', 'Zari Jamni']
};

export const districtCoords = {
  'Mumbai City': [18.9220, 72.8347],
  'Mumbai Suburban': [19.1238, 72.8433],
  'Pune': [18.5204, 73.8567],
  'Nagpur': [21.1458, 79.0882],
  'Thane': [19.2183, 72.9781],
  'Nashik': [19.9975, 73.7898],
  'Aurangabad': [19.8762, 75.3433],
  'Solapur': [17.6599, 75.9064],
  'Amravati': [20.9320, 77.7523],
  'Kolhapur': [16.7050, 74.2433],
  'Akola': [20.7002, 77.0082],
  'Ahmednagar': [19.0948, 74.7480],
  'Beed': [18.9891, 75.7601],
  'Bhandara': [21.1717, 79.6534],
  'Buldhana': [20.5287, 76.1841],
  'Chandrapur': [19.9511, 79.2961],
  'Dhule': [20.9026, 74.7749],
  'Gadchiroli': [20.0988, 80.0003],
  'Gondia': [21.4623, 80.1947],
  'Hingoli': [19.7212, 77.1002],
  'Jalgaon': [21.0077, 75.5626],
  'Jalna': [19.8410, 75.8864],
  'Latur': [18.4088, 76.5603],
  'Nanded': [19.1383, 77.3210],
  'Nandurbar': [21.3732, 74.2415],
  'Osmanabad': [18.1857, 76.0418],
  'Palghar': [19.6936, 72.7655],
  'Parbhani': [19.2644, 76.7751],
  'Raigad': [18.5284, 73.0039],
  'Ratnagiri': [16.9902, 73.3120],
  'Sangli': [16.8524, 74.5815],
  'Satara': [17.6805, 73.9803],
  'Sindhudurg': [16.0360, 73.5590],
  'Wardha': [20.7453, 78.6022],
  'Washim': [20.1011, 77.1350],
  'Yavatmal': [20.3888, 78.1204]
};
